
import type { Metadata } from "next";
import "./globals.css";
import { Lato } from "next/font/google";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/Layout/Tema/theme-provider";
import { CircleCheck, CircleAlert, TriangleAlert, Info } from "lucide-react";
import LayoutClient from "@/components/Layout/LayoutCkient";


const neueMontreal = localFont({
  src: [
    {
      path: "../public/Fonts/NeueMontreal-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/Fonts/NeueMontreal-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/Fonts/NeueMontreal-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/Fonts/NeueMontreal-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/Fonts/NeueMontreal-Italic.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/Fonts/NeueMontreal-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/Fonts/NeueMontreal-MediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/Fonts/NeueMontreal-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    }
  ],
  variable: "--font-heading",
  display: "swap",
});


const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Arquitectura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="es" className={` ${neueMontreal.variable} h-full`} suppressHydrationWarning data-scroll-behavior="smooth">
      <body className={` ${lato} bg-surface/70 dark:bg-background h-full overflow-x-hidden scrollbar-soft`}>
        {children}
      </body >
    </html >
  );
}
