export const primitives = {
  button: [
    'import { Button } from "@agustin/ui/primitives"',
    "",
    '<Button variant="default" size="default">Click me</Button>',
    '<Button variant="outline" size="sm">Outline Small</Button>',
    '<Button variant="destructive" disabled>Delete</Button>',
  ].join("\n"),

  input: [
    'import { Input } from "@agustin/ui/primitives"',
    'import { Search } from "lucide-react"',
    "",
    '<Input placeholder="Buscar..." iconLeft={<Search className="w-4 h-4" />} />',
    '<Input variant="destructive" placeholder="Error" />',
    '<Input type="password" placeholder="Contraseña" iconRight={<Eye />} />',
  ].join("\n"),

  textarea: [
    'import { Textarea } from "@agustin/ui/primitives"',
    "",
    '<Textarea placeholder="Escribe tu mensaje..." rows={4} />',
    '<Textarea variant="destructive" placeholder="Error" />',
  ].join("\n"),

  select: [
    'import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@agustin/ui/primitives"',
    "",
    "<Select value={value} onValueChange={setValue}>",
    "  <SelectTrigger>",
    '    <SelectValue placeholder="Seleccionar..." />',
    "  </SelectTrigger>",
    "  <SelectContent>",
    '    <SelectItem value="apple">Manzana</SelectItem>',
    '    <SelectItem value="banana">Plátano</SelectItem>',
    "  </SelectContent>",
    "</Select>",
  ].join("\n"),

  searchableSelect: [
    'import { SearchableSelect } from "@agustin/ui/primitives"',
    "",
    "<SearchableSelect",
    "  value={value}",
    "  onValueChange={setValue}",
    '  options={[',
    '    { value: "react", label: "React" },',
    '    { value: "vue", label: "Vue" },',
    "  ]}",
    '  placeholder="Framework..."',
    '  searchPlaceholder="Buscar..."',
    "/>",
  ].join("\n"),

  avatar: [
    'import { Avatar, AvatarImage, AvatarFallback } from "@agustin/ui/primitives"',
    "",
    '<Avatar size="default">',
    '  <AvatarImage src="/photo.jpg" alt="User" />',
    "  <AvatarFallback>CN</AvatarFallback>",
    "</Avatar>",
    "",
    '<Avatar size="lg">',
    "  <AvatarFallback>AG</AvatarFallback>",
    "</Avatar>",
  ].join("\n"),

  checkbox: [
    'import { Checkbox } from "@agustin/ui/primitives"',
    "",
    '<Checkbox checked={true} onCheckedChange={setChecked} />',
    "<Checkbox disabled />",
  ].join("\n"),

  switch: [
    'import { Switch } from "@agustin/ui/primitives"',
    "",
    '<Switch checked={true} onCheckedChange={setChecked} />',
    '<Switch size="sm" checked={false} />',
  ].join("\n"),

  radioGroup: [
    'import { RadioGroup, RadioGroupItem } from "@agustin/ui/primitives"',
    "",
    "<RadioGroup value={value} onValueChange={setValue}>",
    '  <div className="flex items-center gap-2">',
    '    <RadioGroupItem value="opt1" id="r1" />',
    '    <label htmlFor="r1">Opción 1</label>',
    "  </div>",
    '  <div className="flex items-center gap-2">',
    '    <RadioGroupItem value="opt2" id="r2" />',
    '    <label htmlFor="r2">Opción 2</label>',
    "  </div>",
    "</RadioGroup>",
  ].join("\n"),

  popover: [
    'import { Popover, PopoverTrigger, PopoverContent } from "@agustin/ui/primitives"',
    "",
    "<Popover>",
    "  <PopoverTrigger asChild>",
    '    <Button>Abrir</Button>',
    "  </PopoverTrigger>",
    "  <PopoverContent>",
    "    <p>Contenido del popover</p>",
    "  </PopoverContent>",
    "</Popover>",
  ].join("\n"),

  collapsible: [
    'import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@agustin/ui/primitives"',
    "",
    '<Collapsible open={open} onOpenChange={setOpen}>',
    "  <CollapsibleTrigger asChild>",
    '    <Button variant="ghost" size="sm">Toggle</Button>',
    "  </CollapsibleTrigger>",
    "  <CollapsibleContent>",
    "    <p>Contenido oculto</p>",
    "  </CollapsibleContent>",
    "</Collapsible>",
  ].join("\n"),

  dropdownMenu: [
    'import { DropdownMenu } from "@agustin/ui/primitives"',
    "",
    "<DropdownMenu",
    '  trigger={<Button variant="outline">Menú</Button>}',
    "  groups={[",
    "    {",
    "      items: [",
    '        { label: "Perfil", icon: <User /> },',
    '        { label: "Configuración", icon: <Settings /> },',
    "      ]",
    "    },",
    "    {",
    '      groupLabel: "Acciones",',
    "      items: [",
    '        { label: "Eliminar", variant: "danger" },',
    "      ]",
    "    }",
    "  ]}",
    "/>",
  ].join("\n"),

  separator: [
    'import { Separator } from "@agustin/ui/primitives"',
    "",
    '<Separator className="my-4" />',
    '<Separator orientation="vertical" className="mx-4 h-8" />',
  ].join("\n"),

  skeleton: [
    'import { Skeleton } from "@agustin/ui/primitives"',
    "",
    '<Skeleton className="h-4 w-full" />',
    '<Skeleton className="h-4 w-3/4" />',
    '<Skeleton className="h-12 w-12 rounded-full" />',
  ].join("\n"),

  sheet: [
    'import { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@agustin/ui/primitives"',
    "",
    "<Sheet>",
    "  <SheetTrigger asChild>",
    '    <Button>Abrir panel</Button>',
    "  </SheetTrigger>",
    '  <SheetContent side="right">',
    "    <SheetHeader>",
    "      <SheetTitle>Título</SheetTitle>",
    "      <SheetDescription>Descripción</SheetDescription>",
    "    </SheetHeader>",
    "    <div>Contenido</div>",
    "  </SheetContent>",
    "</Sheet>",
  ].join("\n"),

  dataTable: [
    'import { DataTable } from "@agustin/ui/primitives"',
    "",
    "const columns = [",
    '  { key: "name", header: "Nombre", align: "left" },',
    '  { key: "email", header: "Email", align: "left" },',
    "]",
    "",
    "<DataTable",
    "  data={users}",
    "  columns={columns}",
    '  rowKey="id"',
    '  size="md"',
    '  headerVariant="default"',
    "  isLoading={false}",
    "/>",
  ].join("\n"),

  tabs: [
    'import { Tabs } from "@agustin/ui/primitives"',
    "",
    "const tabs = [",
    '  { id: "general", label: "General", content: <GeneralPanel /> },',
    '  { id: "security", label: "Seguridad", content: <SecurityPanel /> },',
    "]",
    "",
    '<Tabs tabs={tabs} variant="underline" align="start" />',
  ].join("\n"),

  tooltip: [
    'import { Tooltip } from "@agustin/ui/primitives"',
    "",
    '<Tooltip content="Guardar cambios" side="top">',
    "  <Button>Guardar</Button>",
    "</Tooltip>",
    "",
    '<Tooltip content="Info detallada" variant="rich" side="bottom">',
    '  <Button variant="outline">Info</Button>',
    "</Tooltip>",
  ].join("\n"),
}

export const components = {
  labelBadge: [
    'import { LabelBadge } from "@agustin/ui/components"',
    "",
    '<LabelBadge label="Activo" color="success" variant="soft" size="md" />',
    '<LabelBadge label="Error" color="error" variant="filled" />',
    '<LabelBadge label="Removible" onRemove={() => handleRemove()} icon={<AlertTriangle />} />',
  ].join("\n"),

  label: [
    'import { Label } from "@agustin/ui/components"',
    "",
    '<Label htmlFor="email">Correo electrónico</Label>',
    '<input id="email" type="email" placeholder="usuario@ejemplo.com" />',
  ].join("\n"),

  passwordInput: [
    'import { PasswordInput } from "@agustin/ui/components"',
    "",
    '<PasswordInput placeholder="Ingresa tu contraseña" />',
    "<PasswordInput disabled placeholder=\"Deshabilitado\" />",
  ].join("\n"),

  passwordStrength: [
    'import { PasswordInput, PasswordStrength, isPasswordValid } from "@agustin/ui/components"',
    "",
    'const [password, setPassword] = useState("")',
    "",
    '<PasswordInput value={password} onChange={(e) => setPassword(e.target.value)} />',
    "<PasswordStrength password={password} />",
    "",
    "// Función utilitaria",
    "if (isPasswordValid(password)) {",
    "  // La contraseña cumple todos los requisitos",
    "}",
  ].join("\n"),

  calendar: [
    'import { Calendar } from "@agustin/ui/components"',
    "",
    "// Calendario embebido",
    '<Calendar variant="full" selectionMode="date" label="Fecha de nacimiento" />',
    "",
    "// Calendario en popover",
    '<Calendar variant="input" selectionMode="month" />',
    "",
    "// Con restricciones",
    "<Calendar",
    "  minDate={new Date(2024, 0, 1)}",
    "  maxDate={new Date(2024, 11, 31)}",
    "  value={selectedDate}",
    "  onChange={setSelectedDate}",
    "/>",
  ].join("\n"),

  graficaBar: [
    'import GraficaBar from "@agustin/ui/components"',
    "",
    "<GraficaBar",
    "  data={[",
    '    { label: "Ene", value: 40 },',
    '    { label: "Feb", value: 65 },',
    "  ]}",
    '  title="Ventas mensuales"',
    "  height={240}",
    "  barRadius={4}",
    "/>",
  ].join("\n"),

  graficaDonut: [
    'import GraficaDonut from "@agustin/ui/components"',
    "",
    "<GraficaDonut",
    "  data={[",
    '    { value: 45, label: "Ventas directas" },',
    '    { value: 25, label: "Online" },',
    "  ]}",
    '  title="Canales de venta"',
    "  size={300}",
    "  showTotal={true}",
    "/>",
  ].join("\n"),

  graficaLine: [
    'import GraficaLine from "@agustin/ui/components"',
    "",
    "<GraficaLine",
    "  data={[",
    '    { label: "Lun", value: 30 },',
    '    { label: "Mar", value: 45 },',
    "  ]}",
    '  title="Actividad semanal"',
    "  showArea={true}",
    "  height={240}",
    "/>",
  ].join("\n"),

  emptyState: [
    'import { EmptyState } from "@agustin/ui/components"',
    'import { Inbox } from "lucide-react"',
    "",
    "<EmptyState",
    "  icon={Inbox}",
    '  title="No hay resultados"',
    '  description="Intenta con otros filtros."',
    "  action={<Button>Limpiar filtros</Button>}",
    "/>",
  ].join("\n"),

  card: [
    'import { Card, CardHeader, CardBody, CardFooter } from "@agustin/ui/components"',
    "",
    '<Card variant="elevated">',
    '  <CardHeader title="Título" subtitle="Subtítulo" action={<Button>Editar</Button>} />',
    "  <CardBody>",
    "    <p>Contenido de la card</p>",
    "  </CardBody>",
    '  <CardFooter align="right">',
    '    <Button variant="ghost">Cancelar</Button>',
    "    <Button>Guardar</Button>",
    "  </CardFooter>",
    "</Card>",
  ].join("\n"),

  dialog: [
    'import { Dialog, DialogHeader, DialogBody, DialogFooter } from "@agustin/ui/components"',
    "",
    "const [open, setOpen] = useState(false)",
    "",
    '<Button onClick={() => setOpen(true)}>Abrir</Button>',
    "",
    "<Dialog open={open} onClose={() => setOpen(false)} variant=\"default\" size=\"md\">",
    '  <DialogHeader title="Confirmar acción" description="¿Estás seguro?" />',
    "  <DialogBody>",
    "    <p>Contenido del diálogo</p>",
    "  </DialogBody>",
    '  <DialogFooter align="right">',
    '    <Button variant="ghost" onClick={() => setOpen(false)}>Cancelar</Button>',
    '    <Button onClick={() => setOpen(false)}>Aceptar</Button>',
    "  </DialogFooter>",
    "</Dialog>",
  ].join("\n"),

  alertDialog: [
    'import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@agustin/ui/components"',
    "",
    "<AlertDialog>",
    "  <AlertDialogTrigger asChild>",
    '    <Button variant="destructive">Eliminar</Button>',
    "  </AlertDialogTrigger>",
    "  <AlertDialogContent>",
    "    <AlertDialogHeader>",
    '      <AlertDialogTitle>¿Estás seguro?</AlertDialogTitle>',
    "      <AlertDialogDescription>No se puede deshacer.</AlertDialogDescription>",
    "    </AlertDialogHeader>",
    "    <AlertDialogFooter>",
    "      <AlertDialogCancel>Cancelar</AlertDialogCancel>",
    "      <AlertDialogAction>Eliminar</AlertDialogAction>",
    "    </AlertDialogFooter>",
    "  </AlertDialogContent>",
    "</AlertDialog>",
  ].join("\n"),

  confirmDeleteDialog: [
    'import { ConfirmDeleteDialog } from "@agustin/ui/components"',
    "",
    "const [open, setOpen] = useState(false)",
    "",
    '<Button variant="destructive" onClick={() => setOpen(true)}>Eliminar</Button>',
    "",
    "<ConfirmDeleteDialog",
    "  open={open}",
    "  onOpenChange={setOpen}",
    '  itemName="Usuario #1234"',
    "  onConfirm={() => handleDelete()}",
    "  loading={isDeleting}",
    "/>",
  ].join("\n"),

  pagination: [
    'import { Pagination } from "@agustin/ui/components"',
    "",
    "const [page, setPage] = useState(1)",
    "",
    "<Pagination page={page} totalPages={20} onPageChange={setPage} />",
    "",
    "// Retorna null si totalPages <= 1",
  ].join("\n"),

  breadcrumb: [
    'import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator } from "@agustin/ui/components"',
    "",
    "<Breadcrumb>",
    "  <BreadcrumbList>",
    "    <BreadcrumbItem>",
    '      <BreadcrumbLink href="/">Inicio</BreadcrumbLink>',
    "    </BreadcrumbItem>",
    "    <BreadcrumbSeparator />",
    "    <BreadcrumbItem>",
    "      <BreadcrumbPage>Detalle</BreadcrumbPage>",
    "    </BreadcrumbItem>",
    "  </BreadcrumbList>",
    "</Breadcrumb>",
  ].join("\n"),
}
